# Generated by Django 3.2.9 on 2022-02-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yohou', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='brands_bag',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
