# Generated by Django 3.2.9 on 2022-02-13 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yohou', '0002_auto_20220213_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='weather',
        ),
    ]
