# Generated by Django 3.2.9 on 2022-02-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yohou', '0003_remove_post_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='season',
            field=models.IntegerField(choices=[(1, '春'), (2, '夏'), (3, '秋'), (4, '冬')], null=True),
        ),
    ]
