# Generated by Django 3.2.9 on 2022-02-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yohou', '0004_post_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brands_onpiece',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
