# Generated by Django 3.2.9 on 2022-02-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yohou', '0008_alter_post_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'WOMEN'), (2, 'MEN'), (3, 'KIDS')])),
                ('start_temp', models.IntegerField()),
                ('end_temp', models.IntegerField()),
                ('season', models.IntegerField(choices=[(1, '春'), (2, '夏'), (3, '秋'), (4, '冬')], null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='static/media/advices')),
            ],
        ),
    ]
