# Generated by Django 3.2.9 on 2022-03-06 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yohou', '0009_advice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='username',
        ),
    ]
