# Generated by Django 3.2.9 on 2022-03-10 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yohou', '0011_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
