# Generated by Django 3.2.9 on 2022-03-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yohou', '0012_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(blank=True, max_length=30, null=True)),
                ('season_icon', models.ImageField(upload_to='static/media/season_icon')),
            ],
        ),
    ]
